### ISSUE TITLE
`agentstack/test/pyproject.toml` has a duplicate keys under `scripts` section

### ISSUE THREAD

**Issue by the-praxs** [AgentOps-AI/AgentStack#15]
```toml
[tool.poetry.scripts]
test = "test.main:run"
run_crew = "test.main:run"
train = "test.main:train"
replay = "test.main:replay"
test = "test.main:test"
```

first key should be removed I think
