### ISSUE TITLE
Bug: Tools List has duplicate category names

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#179]
running `agentstack tools list` right now shows this output:

browsing and computer-control have redundant categories

```
Available AgentStack Tools:

web-retrieval:
  - exa: https://exa.ai

browsing:
  - browserbase: https://github.com/browserbase/python-sdk

application-specific:
  - stripe: https://github.com/stripe/agent-toolkit

computer-control:
  - file_read: https://github.com/crewAIInc/crewAI-tools/tree/main/crewai_tools/tools/file_read_tool
  - directory_search: https://github.com/crewAIInc/crewAI-tools/tree/main/crewai_tools/tools/directory_search_tool

vision:
  - vision: AgentStack default tool

database:
  - neon: https://github.com/neondatabase/neon

search:
  - perplexity: https://perplexity.ai

unified-apis:
  - composio: https://composio.dev/

code-execution:
  - open_interpreter: https://github.com/OpenInterpreter/open-interpreter
  - code_interpreter: AgentStack default tool

storage:
  - mem0: https://github.com/mem0ai/mem0

browsing:
  - firecrawl: https://www.firecrawl.dev/

computer-control:
  - ftp: AgentStack default tool

network-protocols:
  - agent_connect: https://github.com/chgaowei/AgentConnect


✨ Add a tool with: agentstack tools add <tool_name>
   https://docs.agentstack.sh/tools/core
```
